/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyLocationRouteImport } from './routes/verify-location'
import { Route as MeRouteImport } from './routes/me'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRoomsIndexRouteImport } from './routes/admin.rooms.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminRoomsRoomIdRouteImport } from './routes/admin.rooms.$roomId'

const VerifyLocationRoute = VerifyLocationRouteImport.update({
  id: '/verify-location',
  path: '/verify-location',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsIndexRoute = AdminRoomsIndexRouteImport.update({
  id: '/admin/rooms/',
  path: '/admin/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoomIdRoute = AdminRoomsRoomIdRouteImport.update({
  id: '/admin/rooms/$roomId',
  path: '/admin/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/me': typeof MeRoute
  '/verify-location': typeof VerifyLocationRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/me': typeof MeRoute
  '/verify-location': typeof VerifyLocationRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin': typeof AdminIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/rooms': typeof AdminRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/me': typeof MeRoute
  '/verify-location': typeof VerifyLocationRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocked'
    | '/me'
    | '/verify-location'
    | '/admin/login'
    | '/admin/reports'
    | '/rooms/$roomId'
    | '/admin/'
    | '/rooms/'
    | '/admin/rooms/$roomId'
    | '/admin/users/$userId'
    | '/admin/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/me'
    | '/verify-location'
    | '/admin/login'
    | '/admin/reports'
    | '/rooms/$roomId'
    | '/admin'
    | '/rooms'
    | '/admin/rooms/$roomId'
    | '/admin/users/$userId'
    | '/admin/rooms'
  id:
    | '__root__'
    | '/'
    | '/blocked'
    | '/me'
    | '/verify-location'
    | '/admin/login'
    | '/admin/reports'
    | '/rooms/$roomId'
    | '/admin/'
    | '/rooms/'
    | '/admin/rooms/$roomId'
    | '/admin/users/$userId'
    | '/admin/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedRoute: typeof BlockedRoute
  MeRoute: typeof MeRoute
  VerifyLocationRoute: typeof VerifyLocationRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  AdminRoomsRoomIdRoute: typeof AdminRoomsRoomIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminRoomsIndexRoute: typeof AdminRoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-location': {
      id: '/verify-location'
      path: '/verify-location'
      fullPath: '/verify-location'
      preLoaderRoute: typeof VerifyLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms/': {
      id: '/admin/rooms/'
      path: '/admin/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms/$roomId': {
      id: '/admin/rooms/$roomId'
      path: '/admin/rooms/$roomId'
      fullPath: '/admin/rooms/$roomId'
      preLoaderRoute: typeof AdminRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedRoute: BlockedRoute,
  MeRoute: MeRoute,
  VerifyLocationRoute: VerifyLocationRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  AdminRoomsRoomIdRoute: AdminRoomsRoomIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminRoomsIndexRoute: AdminRoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
